# Generated by Django 4.2.3 on 2023-07-19 14:32

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('director', models.CharField(max_length=20)),
                ('stars', models.CharField(max_length=50)),
                ('visits', models.IntegerField(blank=True, null=True)),
                ('trailer', models.URLField()),
                ('image', models.URLField()),
                ('length', models.CharField(max_length=20)),
                ('seasons', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('genres', models.ManyToManyField(to='common.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('director', models.CharField(max_length=20)),
                ('stars', models.CharField(max_length=50)),
                ('visits', models.IntegerField(blank=True, null=True)),
                ('trailer', models.URLField()),
                ('image', models.URLField()),
                ('length', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('genres', models.ManyToManyField(to='common.genre')),
            ],
        ),
    ]
