# Generated by Django 4.2.3 on 2023-07-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='series',
            name='director',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='series',
            name='length',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='stars',
            field=models.CharField(max_length=60),
        ),
    ]
