# Generated by Django 4.2.3 on 2023-07-27 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_movie_name_alter_series_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='series',
            name='director',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='series',
            name='stars',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
