# Generated by Django 4.2.3 on 2023-07-27 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_movie_director_alter_movie_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
