# Generated by Django 4.2.3 on 2023-07-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_movie_name_alter_series_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='episodes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='seasons',
            field=models.PositiveIntegerField(),
        ),
    ]
