# Generated by Django 4.2.3 on 2023-07-28 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_series_episodes_alter_series_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='episodes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='series',
            name='seasons',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
