# Generated by Django 4.2.3 on 2023-07-29 16:31

import cinema_critic_server.content.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_series_episodes_alter_series_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='series',
            name='type',
            field=models.CharField(default='series', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), cinema_critic_server.content.validators.validate_current_year]),
        ),
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), cinema_critic_server.content.validators.validate_current_year]),
        ),
    ]
