# Generated by Django 4.2.3 on 2023-08-19 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_movie_name_alter_series_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=65, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=65, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
