# Generated by Django 4.2.3 on 2023-07-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('action', 'Action'), ('animation', 'Animation'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('drama', 'Drama'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('romance', 'Romance')], max_length=20, unique=True)),
            ],
        ),
    ]
