# Generated by Django 4.2.3 on 2023-07-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20230719_1616'),
    ]

    operations = [
    ]
