# Generated by Django 4.2.3 on 2023-07-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('accounts', '0002_profile_city_profile_country_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarked_movies',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='content.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarked_series',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='content.series'),
        ),
    ]
