# Generated by Django 4.2.3 on 2023-07-26 12:22

import cinema_critic_server.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2), cinema_critic_server.accounts.validators.name_contains_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2), cinema_critic_server.accounts.validators.name_contains_only_letters]),
        ),
    ]
