# Generated by Django 4.2.3 on 2023-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_movie_type_series_type_alter_movie_year_and_more'),
        ('accounts', '0007_alter_profile_city_alter_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookmarked_movies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bookmarked_series',
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarks_movies',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_movies', to='content.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarks_series',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_series', to='content.series'),
        ),
    ]
